name: Build & Deploy to Firebase Hosting

on:
  push:
    branches: [ master ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      
      - name: Install build dependencies
        run: npm install --only=dev
      
      - name: Build
        run: grunt build
      
      - name: Install deploy dependencies
        run: npm install -g firebase-tools
      
      - name: Deploy to Firebase Hosting
        run: firebase deploy --token "$FIREBASE_TOKEN" --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
